### ISSUE TITLE
Caffe2 setup problem 

### ISSUE THREAD

**Issue by Xiaoyang-Rebecca** [dongfangduoshou123/Caffe2-yolo-v3#1]
Hi 

I have caffe2 install on my machine (i.e. python "import caffe2" works) and want to test run the **demo.py**.
I am confused about your description in the first step of **Intall the YOLOModule**.

1) In order to create the **libcaffe2_yolo_ops_gpu.so**, what do you mean by "cut yolo page to module folder"?
FYI,I install the caffe2 from [caffe2.ai](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=prebuilt) using conda install

2) Where can I load the path of my existing caffe2? 

If you happen to speak Chinese, more than welcome to answer it in Chinese.

Thanks

**Comment by dongfangduoshou123** [comment]
build from source.

**Comment by dongfangduoshou123** [comment]
caffe2从源码编译安装。。那段描述的意思是，将Yolo文件夹放到Caffe2-master下的modules文件夹下，然后在modules文件夹里的Cmake lists. txt内将添加一行内容:add_subdirectory(Yolo)。
然后重新编译安装就会得到那个so

**Comment by dongfangduoshou123** [comment]
make install -j8如果成功了，会在/ usr/ local/ lib看到libcaffe2_yolo_ops_gpu.so。。

**Comment by Xiaoyang-Rebecca** [comment]
Thank you very much!


*_____________________________________________*
*Xiaoyang LI  (Rebecca)*

Ph.D. Candidate in Image Processing and Data Analytics
Graduate Affairs Chair of IEEE-UH Student Branch
Department of Electrical and Computer Engineering, University of Houston



On Fri, Jun 8, 2018 at 2:01 AM, dongfangduoshou123 <notifications@github.com
