### ISSUE TITLE
how to convert the "*.weights" file to the model file

### ISSUE THREAD

**Issue by 11rocky** [dongfangduoshou123/Caffe2-yolo-v3#4]
I want to know how to convert the "*.weights" file to the model file? is there any tools or projects? Thanks very much!

**Comment by InvictusY** [comment]
I have the problem, can you tell us ? thank you !

**Comment by lchia** [comment]
same question, thank you

**Comment by alexbuyval** [comment]
I cannot download the model file from the Baidu disk, so I have the same question too.

Thank you!

**Comment by dongfangduoshou123** [comment]
I convert script is not mature，recently I was attempted to reproducing the train pipline in caffe2. so Sorry, please wait sometime for the convert and train code.

 alexbuyval You can not access Baidu?

**Comment by alexbuyval** [comment]
@dongfangduoshou123 Finally, I have downloaded the weights from Baidu. Thank you!

**Comment by dongfangduoshou123** [comment]
Run cppDemo in newest caffe2 may have some errors,See this issue to solve.   https://github.com/dongfangduoshou123/Caffe2-yolo-v3/issues/2

**Comment by wwint-lau** [comment]
I can't download from Baidu too.  Need a baidu account and in turn need a china cell phone number.  Pleae help.

**Comment by abx67** [comment]
> I convert script is not mature，recently I was attempted to reproducing the train pipline in caffe2. so Sorry, please wait sometime for the convert and train code.
> 
> alexbuyval You can not access Baidu?

Hi appreciate you work for this. So I  want to follow up if the train pipline is ready?
