### ISSUE TITLE
I have some problems in main.cpp, Can you help me？

### ISSUE THREAD

**Issue by InvictusY** [dongfangduoshou123/Caffe2-yolo-v3#5]
I've compiled it successfully and can run the python example properly. But the main.cpp file keeps reporting errors。I found error in Line 86：CAFFE_ENFORCE(workspace.RunNet(predictnet.name()));
and  GetTensorToHost function in boxuitl.h . I can't make it. Can you help me?  Thanks!
The error is ：
 terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

**Comment by dongfangduoshou123** [comment]
You use the newest Caffe2?
In this issue(https://github.com/dongfangduoshou123/Caffe2-yolo-v3/issues/2) , I have say some thing about this-----------the newest caffe2 Tensor class( removed the template); I have updated .h and .cc to adapt this change, Please try complied again; may be the cppdemo's .h and .cc files should also make some change yourself about the Tensor,remove the template declare.



If you solve the problem ,pelase pull the right main.cpp to this repo,Thank you! 
else then tell me.
