### ISSUE TITLE
.pbtxt files are bad? Need non-txt PB files?

### ISSUE THREAD

**Issue by nkorem-intel** [dongfangduoshou123/Caffe2-yolo-v3#7]
Hi looks like the .pbtxt files are not OK - I cannot read them...?
I'm trying to read them like this:

```
    device_opts = core.DeviceOption(caffe2_pb2.CPU)
    net_def = caffe2_pb2.NetDef()

    filename_prefix = 'param_init_net'
    with open(filename_prefix+'.pbtxt', 'r') as f:
        file_content = f.read()
        text_format.Merge(file_content, net_def, True, True)
        with open(filename_prefix+'.pb', "wb") as fout:
            fout.write(net_def.SerializeToString())
```

Do you have them in .PB format?
Thanks,
N

**Comment by dongfangduoshou123** [comment]
No Need txt PB files, 
std::string init_net = "/opt/caffe2_yolov3/init_net.pb";
and
std::string predict_net = "/opt/caffe2_yolov3/predict_net.pb";
is enough.  Plaease use these two pb model file from the download link, modelfile dir's file may be not ok.

**Comment by nkorem-intel** [comment]
Thanks, understand.
Any chance you can upload init_net.pb to github? I'm still struggling with baidu download

Thanks,
N

**Comment by dongfangduoshou123** [comment]
too big, githbub has File size limit。

**Comment by nkorem-intel** [comment]
Understood.
Currently I cannot download from Baidu, cannot sign up for it. If you have the files on some other file shareI will try.

Thx
N

**Comment by dongfangduoshou123** [comment]
QQ? where are you from?

**Comment by nkorem-intel** [comment]
I'm from Israel / US.
MS Onedrive, google drive, dropbox, ...?

**Comment by wwint-lau** [comment]
Same problem.  Can't download the weights from Baidu.

**Comment by dongfangduoshou123** [comment]
MS Onedrive, google drive, dropbox, ... Cannot access in china.....

**Comment by wwint-lau** [comment]
The problem was the original file is too big to upload into GitHub right?
What if we split the file into smaller pieces?
